### ISSUE TITLE
Authentication Fails Do To Target Machine Actively Refusing

### ISSUE THREAD

**Issue by gist901** [MatMaul/pynetgear#110]
Hi there,

I have run into authentication issue where I receive the following error:

`Max retries exceeded with url: /soap/server_sa/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E25540B520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it`

I am currently running pynetgear version `.91`.

I have also tried as you suggested `netgear.login_try_port()` and receive the error stated above for each connection attempt:
`login using all known port-ssl combinations failed.
Out[3]: False`

Here is the full error output for one of the connection attempts:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cth\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\cth\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\cth\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\cth\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Users\cth\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001E25540B520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by GeraldPape** [comment]
on my ORBI I just need port 80, without SSL, tried that?

**Comment by starkillerOG** [comment]
did you try rebooting the router and then trying netgear.login_try_port()

**Comment by starkillerOG** [comment]
could you please also specify the host using IP and the username as well as the password while initializing the Netgear class?
