### ISSUE TITLE
Error with Netgear R9000

### ISSUE THREAD

**Issue by Swagielka** [MatMaul/pynetgear#41]
Hey there!

Just wanted to let you know, that the python script doesn't seem to work with an R9000 Nighthawk x10.
The router runs on the newest firmware: V1.0.4.2

This is the error log from home assistant:

```
2018-06-26 11:48:57 INFO (SyncWorker_13) [pynetgear] Get attached devices
2018-06-26 11:48:57 INFO (SyncWorker_13) [pynetgear] Login
2018-06-26 11:48:57 ERROR (SyncWorker_13) [pynetgear] Error talking to API

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
raise err
File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
self.send(msg)
File "/usr/local/lib/python3.6/http/client.py", line 964, in send
self.connect()
File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
self, "Failed to establish a new connection: %s" % e)

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x148d3e4fd9b0>: Failed to establish a new connection: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
timeout=timeout
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.2.1', port=5000): Max retries exceeded with url: /soap/server_sa/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x148d3e4fd9b0>: Failed to establish a new connection: [Errno 111] Connection refused',))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/pynetgear/__init__.py", line 236, in _make_request
data=message, timeout=10, verify=False)
File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.2.1', port=5000): Max retries exceeded with url: /soap/server_sa/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x148d3e4fd9b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

2018-06-26 11:48:57 ERROR (SyncWorker_13) [homeassistant.components.device_tracker.netgear] Failed to Login

2018-06-26 11:48:57 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform netgear
```

Greetings!

**Comment by MatMaul** [comment]
did you force the router address/ip in the config file ?
If yes try to remove it and see if the autodetect works.
You can also try to manually tweak the port, which default to 5000, try 80 or 443, and play with ssl boolean parameter.

**Comment by Swagielka** [comment]
Ha! It was indeed the port!
Worked right away when using the port 80.
I guess you can add the R9000 to the known working devices list. :)

Thanks alot!
