### ISSUE TITLE
command line throws requests.exceptions.MissingSchema

### ISSUE THREAD

**Issue by GeraldPape** [MatMaul/pynetgear#87]
using a python code file to login or to get traffic meter works without throwing an error, using the same on the command line however throws requests.exceptions.MissingSchema

this works: (with correct values for password, etc)
```
from pynetgear import Netgear

netgear = Netgear(password="*****", host="******", user="******", ssl=False,port=80)

x=netgear.get_traffic_meter()
```
this not:

python -m pynetgear --user '****' --port '80' --password '****' --url "*******" --no-ssl traffic_meter
Error talking to API
Traceback (most recent call last):
  File "C:\src\jerry\pynetgear\pynetgear\__init__.py", line 480, in _make_request
    response = requests.post(self.soap_url, headers=headers,
  File "C:\Python38\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "C:\Python38\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Python38\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '10.0.0.1/soap/server_sa/': No schema supplied. Perhaps you meant http://10.0.0.1/soap/server_sa/?
Error talking to API
Traceback (most recent call last):
  File "C:\src\jerry\pynetgear\pynetgear\__init__.py", line 480, in _make_request
    response = requests.post(self.soap_url, headers=headers,
  File "C:\Python38\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "C:\Python38\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Python38\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '10.0.0.1/soap/server_sa/': No schema supplied. Perhaps you meant http://******/soap/server_sa/?
Error communicating with the Netgear router

**Comment by MatMaul** [comment]
You should use `--host 10.0.0.1` instead of `--url 10.0.0.1`.
